### ISSUE TITLE
Topic: Feedback on standup

### ISSUE THREAD

**Issue by karelz** [dotnet/corefx-standup#23]
Questions:
* Was the standup useful?
  * If yes, what frequency would you like to see?
* What would you change? (on format, moderation, topic selection, etc.)
* Any suggestions how to involve larger community in the standup?
  * Who should be allowed to 'speak up'? (only core contributors, the rest IM questions only?)
  * How to promote/nominate more contributors into 'core contributors' list? Community nominations with voting?
* Other suggestions?

**Comment by karelz** [comment]
Covered in [2017/6/26 - 1st standup](https://github.com/dotnet/corefx-standup/blob/master/Standups/2017-06.md)

**Comment by shaggygi** [comment]
@karelz It might be informative to gather some of the PMs (you, @terrajobst, @danmosemsft, @weshaggard, @DamianEdwards, etc.) for a future standup to discuss their thoughts on general progress since .NET Core/Standard was created.

For example, what are some of the successes they feel have been accomplished?  What were some of the biggest challenges (completed and/or future) to overcome?  What are some future thoughts/direction for the next few years (of course, without exposing secrets 😉).

I've always found it intriguing to hear a panel of the experts having a fireside chat on the topics.  It would be nice to hear their opinions/thoughts/passion on where this technology is going... understanding what is stated might not necessarily be anything official.
