### ISSUE TITLE
Video is now private, no way to watch

### ISSUE THREAD

**Issue by jnm2** [dotnet/corefx-standup#26]
As I mentioned to @karelz, I've been slammed with work. I only got halfway through the video when the link was given out, and now that I have time to come back to it, I see the video has been made private.

(This is the readme's link: https://www.youtube.com/playlist?list=PLRAdsfhKI4OWA9B347EDadCzpw8VrF0M0.)

Did I miss out permanently? :-( Thanks!

**Comment by jnm2** [comment]
I also see in https://github.com/dotnet/corefx-standup/issues/5:

> Hello everyone, please read the README.md in this repo (incl. explanation why it is now private repo).

But the readme [currently](https://github.com/dotnet/corefx-standup/blob/d3d31368cc047af7d9a470d44e23750bf97b562d/README.md) doesn't say anything about privacy, so clarification on that would be great.

**Comment by karelz** [comment]
Sorry for the inconvenience @jnm2.
The issue #5 talked about the entire repo being private at the moment of its creation. It is public since last week.

Regarding the video: It was a trial and it was not ready for publishing. Sorry for the confusion, I am to blame for it :( - see also explanation [here](https://twitter.com/ziki_cz/status/879944472217255937).
Future stnadups will be steamed live & recorded.
